title: BusConf 2020
description: The Ultimate FP Unconference
year: 2020

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Format
   url: /format
 - title: Schedule
   url: /schedule
 - title: Location
   url: /location
 - title: Tickets
   url: /tickets

social:
   twitter: _BusConf_
